services:
  - type: web
    name: black-russia-monitor
    env: python
    region: frankfurt  # или другой регион
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    plan: free
